//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace Proyecto_Final
{
    
    
    public class Indicadores : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led5;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led6;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led7;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led8;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led9;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led10;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        public Indicadores()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.pictureBox3 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.pictureBox2 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led2 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led4 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led5 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led6 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led7 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led8 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led9 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led10 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // pictureBox3
            // 
            this.pictureBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(439, 291);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(103, 84);
            // 
            // pictureBox2
            // 
            this.pictureBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(548, 275);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(81, 100);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(340, 36);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(44, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font20b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(410, 31);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(191, 42);
            this.tpsLabel3.Title = "Indicadores";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.BackColor = System.Drawing.Color.Coral;
            this.tpsLabel2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(19, 66);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(284, 24);
            this.tpsLabel2.Title = "Mercedes-Benz Srinter 315 CDI";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.BackColor = System.Drawing.Color.Coral;
            this.tpsLabel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(19, 31);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(284, 46);
            this.tpsLabel1.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel1.Title = "Montaje Vidrio Trasero";
            // 
            // led1
            // 
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led1.ForeColor = System.Drawing.Color.Black;
            this.led1.Location = new System.Drawing.Point(9, 139);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(154, 36);
            this.led1.Text = "Potenciador";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font16b;
            this.tpsLabel4.ForeColor = System.Drawing.Color.Black;
            this.tpsLabel4.Location = new System.Drawing.Point(9, 96);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(215, 42);
            this.tpsLabel4.Title = "Etapa Progreso:";
            // 
            // led2
            // 
            this.led2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led2.Location = new System.Drawing.Point(192, 139);
            this.led2.Name = "led2";
            this.led2.Size = new System.Drawing.Size(101, 36);
            this.led2.Text = "Ajuste";
            // 
            // led3
            // 
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(325, 139);
            this.led3.Name = "led3";
            this.led3.Size = new System.Drawing.Size(121, 36);
            this.led3.Text = "Pegante";
            // 
            // led4
            // 
            this.led4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led4.Location = new System.Drawing.Point(468, 139);
            this.led4.Name = "led4";
            this.led4.Size = new System.Drawing.Size(121, 36);
            this.led4.Text = "Montaje";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font16b;
            this.tpsLabel5.ForeColor = System.Drawing.Color.Black;
            this.tpsLabel5.Location = new System.Drawing.Point(12, 192);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(215, 42);
            this.tpsLabel5.Title = "Posición vidrios:";
            // 
            // led5
            // 
            this.led5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led5.Location = new System.Drawing.Point(162, 277);
            this.led5.Name = "led5";
            this.led5.Size = new System.Drawing.Size(121, 36);
            this.led5.Text = "Montaje";
            // 
            // led6
            // 
            this.led6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led6.Location = new System.Drawing.Point(162, 240);
            this.led6.Name = "led6";
            this.led6.Size = new System.Drawing.Size(121, 36);
            this.led6.Text = "Pegante";
            // 
            // led7
            // 
            this.led7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led7.Location = new System.Drawing.Point(12, 277);
            this.led7.Name = "led7";
            this.led7.Size = new System.Drawing.Size(101, 36);
            this.led7.Text = "Ajuste";
            // 
            // led8
            // 
            this.led8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led8.ForeColor = System.Drawing.Color.Black;
            this.led8.Location = new System.Drawing.Point(12, 240);
            this.led8.Name = "led8";
            this.led8.Size = new System.Drawing.Size(154, 36);
            this.led8.Text = "Potenciador";
            // 
            // led9
            // 
            this.led9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led9.Location = new System.Drawing.Point(299, 240);
            this.led9.Name = "led9";
            this.led9.Size = new System.Drawing.Size(121, 36);
            this.led9.Text = "Pegante";
            // 
            // led10
            // 
            this.led10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led10.Location = new System.Drawing.Point(299, 277);
            this.led10.Name = "led10";
            this.led10.Size = new System.Drawing.Size(121, 36);
            this.led10.Text = "Montaje";
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Image = ((System.Drawing.Image)(resources.GetObject("button1.Image")));
            this.button1.Location = new System.Drawing.Point(19, 319);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(89, 56);
            this.button1.Text = "";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // screenForm
            // 
            this.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.Controls.Add(this.button1);
            this.Controls.Add(this.led10);
            this.Controls.Add(this.led9);
            this.Controls.Add(this.led5);
            this.Controls.Add(this.led6);
            this.Controls.Add(this.led7);
            this.Controls.Add(this.led8);
            this.Controls.Add(this.tpsLabel5);
            this.Controls.Add(this.led4);
            this.Controls.Add(this.led3);
            this.Controls.Add(this.led2);
            this.Controls.Add(this.tpsLabel4);
            this.Controls.Add(this.led1);
            this.Controls.Add(this.pictureBox3);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.tpsLabel3);
            this.Controls.Add(this.tpsLabel2);
            this.Controls.Add(this.tpsLabel1);
            this.Controls.SetChildIndex(this.tpsLabel1, 0);
            this.Controls.SetChildIndex(this.tpsLabel2, 0);
            this.Controls.SetChildIndex(this.tpsLabel3, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.Controls.SetChildIndex(this.pictureBox2, 0);
            this.Controls.SetChildIndex(this.pictureBox3, 0);
            this.Controls.SetChildIndex(this.led1, 0);
            this.Controls.SetChildIndex(this.tpsLabel4, 0);
            this.Controls.SetChildIndex(this.led2, 0);
            this.Controls.SetChildIndex(this.led3, 0);
            this.Controls.SetChildIndex(this.led4, 0);
            this.Controls.SetChildIndex(this.tpsLabel5, 0);
            this.Controls.SetChildIndex(this.led8, 0);
            this.Controls.SetChildIndex(this.led7, 0);
            this.Controls.SetChildIndex(this.led6, 0);
            this.Controls.SetChildIndex(this.led5, 0);
            this.Controls.SetChildIndex(this.led9, 0);
            this.Controls.SetChildIndex(this.led10, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling CloseScreen
                this.CloseToMain();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
